//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by microscope.rc
//
#define IDS_BMP_TOO_BIG                 4
#define IDS_CANNOT_LOAD_DIB             5
#define IDS_CANNOT_SAVE_DIB             6
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_MICROSTYPE                  129
#define IDD_MEASURE                     130
#define IDD_BCADJUST                    132
#define IDD_SHOW3D                      133
#define IDR_POPUP_DIALOG                134
#define IDD_ATOMFORCE                   137
#define IDD_ROUGHNESS                   138
#define IDD_SIZE                        139
#define IDD_SINGLESCANNER               140
#define IDC_SETOPTION                   1000
#define IDC_SETBMP                      1001
#define IDC_STATICBMPNAME               1002
#define IDC_BMPNAME                     1003
#define IDC_STATICBMPSIZE               1004
#define IDC_STATICSRANGEX               1012
#define IDC_STATICSMALLRANGEX           1012
#define IDC_SETRANGE                    1013
#define IDC_STATICRANGEY                1014
#define IDC_STATICSMALLRANGEY           1014
#define IDC_Rangex                      1015
#define IDC_SMALLRANGEX                 1015
#define IDC_SPINRANGEX                  1016
#define IDC_SPINRANGESMALLX             1016
#define IDC_STATICIMAGESIZEY            1016
#define IDC_Rangey                      1017
#define IDC_SMALLRANGEY                 1017
#define IDC_SPINRANGEY                  1018
#define IDC_SPINRANGESMALLY             1018
#define IDC_Imagesizex                  1018
#define IDC_SETTIME                     1019
#define IDC_Imagesizey                  1019
#define IDC_STATICLARGERANGEX           1020
#define IDC_STATICLARGERANGEY           1021
#define IDC_LARGERANGEX                 1022
#define IDC_SPINRANGELARGEX             1023
#define IDC_LARGERANGEY                 1024
#define IDC_SPINRANGELARGEY             1025
#define IDC_STARTSCAN                   1026
#define IDC_BUTTONSTARTSCAN             1026
#define IDC_STOPSCAN                    1027
#define IDC_BUTTONSTOPSCAN              1027
#define IDC_SHOWBMP                     1028
#define IDC_STATICPIANZHIX              1029
#define IDC_BMPCAPTURE                  1030
#define IDC_BUTTONBMPCAPTURE            1030
#define IDC_BMPSMALL                    1031
#define IDC_RADIOBMPSIZE                1031
#define IDC_BMPLARGE                    1032
#define IDC_RADIOBMPSIZE2               1032
#define IDC_SLIDERTIME                  1033
#define IDC_PIANZHIX                    1034
#define IDC_STATICPIANZHIY              1035
#define IDC_PIANZHIY                    1036
#define IDC_BUTTONGOBACK                1037
#define IDC_KX                          1038
#define IDC_SPINKX                      1039
#define IDC_KY                          1040
#define IDC_SPINKY                      1041
#define IDC_SHOWTIME                    1042
#define IDC_STATICSHOWX                 1043
#define IDC_STATICSHOWY                 1044
#define IDC_STATICSHOWZ                 1045
#define IDC_STATICSHOWRa                1045
#define IDC_STATICSHOWZMAX              1046
#define IDC_STATICSHOWZMIN              1047
#define IDC_SHOWY                       1048
#define IDC_SHOWX                       1049
#define IDC_SHOWZ                       1050
#define IDC_SHOWXDANWEI                 1050
#define IDC_SHOWZMAX                    1051
#define IDC_SHOWZMIN                    1052
#define IDC_RADIORANGE                  1053
#define IDC_RADIORANGE2                 1054
#define IDC_SHOWYDANWEI                 1055
#define IDC_SHOWZMAXDANWEI              1056
#define IDC_MONTHCALENDAR1              1057
#define IDC_SHOWZMINDANWEI              1057
#define IDC_PIANZHI                     1058
#define IDC_CHECKPIANZHI                1059
#define IDC_SHOWRa                      1060
#define IDC_SPINPIANZHIX                1061
#define IDC_STATICPIANZHIXRANGEX        1062
#define IDC_SPINPIANZHIY                1063
#define IDC_STATICPIANZHIXRANGEY        1064
#define IDC_STATICSHOWRy                1065
#define IDC_SHOWRy                      1066
#define IDC_BRIGHTNESS                  1067
#define IDC_STATICSHOWRz                1067
#define IDC_CONTRASTNESS                1068
#define IDC_SHOWRz                      1068
#define IDC_SLIDERBRIGHTNESS            1069
#define IDC_SHOWRaDANWEI                1069
#define IDC_SLIDERCONTRAST              1070
#define IDC_SHOWRyDANWEI                1070
#define IDC_STATICBRIGHTNESS            1071
#define IDC_SHOWRzDANWEI                1071
#define IDC_STATICCONTRAST              1072
#define IDC_STATICLIGHTNESSTHRESHOLD    1078
#define IDC_SLIDERTHRESHOLD             1079
#define IDC_SHOWTHRESHOLD               1080
#define IDC_SHOWCURVE                   1082
#define IDC_BUTTONSTART                 1083
#define IDC_BUTTONCAPTURE               1084
#define IDC_SLIDERRANGE                 1085
#define IDC_STATICBACKGROUNDCOLOR       1087
#define IDC_STATICCURVECOLOR            1088
#define IDC_BLACKGROUNDCOLOR            1089
#define IDC_BACKGROUNDCOLOR             1089
#define IDC_COORDINAGECOLOR             1090
#define IDC_CURVECOLOR                  1091
#define IDC_STATICCOORDINATE            1092
#define IDC_STATICCOORDINATECOLOR       1092
#define IDC_STATICTIMEFASTER            1093
#define IDC_STATICTIMESLOWER            1094
#define IDC_SHOWRANGE                   1095
#define IDC_COORDINATECOLOR             1097
#define IDC_CURVEIMAGE                  1099
#define IDC_STATICRa                    1101
#define IDC_Ra                          1102
#define IDC_Radanwei                    1103
#define IDC_STATICRy                    1104
#define IDC_Ry                          1105
#define IDC_Rydanwei                    1106
#define IDC_STATICROUGHNESS             1107
#define IDC_STATICSCANRANGE             1108
#define IDC_STATICIMAGESIZE             1109
#define IDC_STATICRz                    1110
#define IDC_Rz                          1111
#define IDC_Rzdanwei                    1112
#define IDC_STATICRANGEX                1113
#define IDC_SMALL                       1114
#define IDC_STATICIMAGESIZEX            1115
#define IDC_BIG                         1115
#define IDC_Rangexdanwei                1116
#define IDC_SCANX                       1116
#define IDC_Rangeydanwei                1117
#define IDC_SPINX                       1117
#define IDC_Imagesizexdanwei            1118
#define IDC_SCANY                       1118
#define IDC_MOUSESELECT                 1118
#define IDC_Imagesizeydanwei            1119
#define IDC_SPINY                       1119
#define IDC_MOUSERANGEXFROM             1119
#define IDC_MOUSERANGEXTO               1120
#define IDC_MOUSERANGEYFROM             1121
#define IDC_MOUSERANGEYTO               1122
#define IDC_STATICX                     1123
#define IDC_STATICY                     1124
#define IDC_SELECTTIMES                 1128
#define IDC_SPINSELECTTIMES             1130
#define IDC_SETTIMES                    1131
#define IDC_ROWSCANTIMETXT              1132
#define IDC_BMPSCANTIMETXT              1133
#define IDC_ROWSCANTIME                 1134
#define IDC_BMPSCANTIME                 1135
#define IDC_SELECTSCANTIME              1136
#define IDC_FINISHSCANTIMESTXT1         1137
#define IDC_FINISHSCANTIMES             1138
#define IDC_FINISHSCANTIMESTXT2         1139
#define IDC_SETTIMES2                   1140
#define IDC_SCANDIRECTION               1152
#define IDC_XDIRECTION                  1153
#define IDC_YDIRECTION                  1154
#define IDC_RADIO1                      1157
#define IDC_SINGLEXSCAN                 1157
#define IDC_SINGLEXSCANTXT              1161
#define IDC_SPINSINGLEXSCANTXT          1163
#define IDC_SINGLEYSCANTXT              1164
#define IDC_SPINSINGLEYSCANTXT          1165
#define IDC_DIRECTION                   1166
#define IDC_SINGLESCAN                  1167
#define IDC_SINGLEYSCAN                 1168
#define IDC_CHECKSINGLESCAN             1169
#define IDC_BMPSCANTIMEDANWEI           1170
#define IDC_ROWSCANTIMEDANWEI           1172
#define IDC_CAPTURE                     1173
#define IDC_GOBACK                      1174
#define IDC_BMPFRAME                    1175
#define IDC_GETDATA                     1178
#define IDC_STOP                        1179
#define IDC_XRATE                       1180
#define IDC_YRATE                       1181
#define IDC_KZ                          1220
#define IDC_SPINKZ                      1222
#define ID_BUTTON32775                  32775
#define ID_MUESURE                      32775
#define ID_MEASURE                      32776
#define ID_MEASURE1                     32781
#define ID_BLUR                         32782
#define ID_3D                           32783
#define IDC_SETCOLOR                    32785
#define IDC_PSEUDOCOLOR                 32786
#define IDC_BCADJUST                    32794
#define ID_POPUP_CLOSE                  32796
#define ID_POPUP_CAPTUREIMAGE           32797
#define ID_POPUP_BACKGROUND             32798
#define ID_POPUP_FRONT                  32799
#define ID_POPUP_ADDCONTRAST            32800
#define ID_POPUP_SUBTRACTCONTRAST       32801
#define ID_POPUP_RESETCONTRAST          32802
#define ID_POPUP_ADDBRIGHTNESS          32804
#define ID_POPUP_SUBTRACTBRIGHTNESS     32805
#define ID_POPUP_RESETBRIGHTNESS        32806
#define ID_POPUP_ADDSOLID               32807
#define ID_POPUP_SUBTRACTSOLID          32808
#define ID_POPUP_RESETSOLID             32809
#define ID_POPUP_IMAGEUPPER             32810
#define ID_POPUP_IMAGELOWER             32811
#define ID_POPUP_IMAGERESET             32812
#define ID_ATOMFORCE                    32815
#define ID_ROUGHNESS                    32821
#define ID_SIZE                         32822
#define ID_POPUP_ADDAXIS                32824
#define ID_POPUP_SUBTRACTAXIS           32825
#define ID_POPUP_ADDLEGEND              32826
#define ID_POPUP_DELETELEGEND           32827
#define ID_POPUP_XROTATE                32829
#define ID_POPUP_YROTATE                32830
#define ID_POPUP_RANDOMROTATE           32832
#define ID_POPUP_STOPTOTATE             32833
#define ID_POPUP_LINE                   32834

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        141
#define _APS_NEXT_COMMAND_VALUE         32835
#define _APS_NEXT_CONTROL_VALUE         1223
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
